---
- hosts: [homeservers, vps]
  remote_user: root
  roles:
    - role: basic
      tags: [install,users,configure]
      vars: 
        basic_list_users:
          - name: belgotux
            primarygroup: belgotux
            groups: sudo,users,staff,adm
            shell: "/bin/zsh"
            passwd: $6$xxxx
            pubkeys:
              - xxx.pub
              - yyy.pub
        # firstuser: belgotux
        # firstusergroup: belgotux
        # firstusershell: "/bin/zsh"
        # firstuserdir: "{{('/home/'+ firstuser)}}"
        bash_alias_shared: yes
        vim_config_shared: yes