---
- hosts: [homeservers, vps]
  remote_user: root
  roles:
    - role: basic
      tags: [install,users,configure]
      vars: 
        firstuser: belgotux
        firstusergroup: belgotux
        firstusershell: "/bin/zsh"
        firstuserdir: "{{('/home/'+ firstuser)}}"
        bash_alias_shared: yes
        vim_config_shared: yes