- name: "staff authorized for {{staff_directories|join(',')}}"
  file:
    dest: "{{item}}"
    state: directory
    mode: 02775 #sticky bit
    group: staff
    owner: root
  loop: "{{staff_directories}}"
  when: staff_directories is defined

- name: merge common and local scripts
  set_fact:
    basic_custom_scripts_common: "{{basic_custom_scripts_common + basic_custom_scripts_local}}"
  when: basic_custom_scripts_common is defined and basic_custom_scripts_local is defined

- name: get only local scripts
  set_fact:
    basic_custom_scripts_common: "{{basic_custom_scripts_local}}"
  when: basic_custom_scripts_common is not defined and basic_custom_scripts_local is defined

- name: Install scripts
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/{{item | basename}}"
    mode: 0775
  loop: "{{basic_custom_scripts_common}}"
  when: basic_custom_scripts_common is defined
  
- name: merge common and local etc
  set_fact:
    basic_custom_etc_common: "{{basic_custom_etc_common + basic_custom_etc_local}}"
  when: basic_custom_etc_common is defined and basic_custom_etc_local is defined
- name: get only local etc
  set_fact:
    basic_custom_etc_common: "{{basic_custom_etc_local}}"
  when: basic_custom_etc_common is not defined and basic_custom_etc_local is defined
- name: Install local etc config files
  copy:
    src: "{{item}}"
    dest: "/usr/local/etc/{{item | basename}}"
    mode: 0660
  loop: "{{basic_custom_etc_common}}"
  when: basic_custom_etc_common is defined

- name: copy custom cron files based on group name
  include_tasks: configure-custom-cron.yml
  loop: "{{group_names}}"
  loop_control:
    loop_var: current_group

  #TODO idem src git?