---
- name: Add udev files
  copy:
    content: "{{ item.value }}"
    dest: "/etc/udev/rules.d/{{ item.dest }}.rules"
  loop: "{{ basic_udev_rules if basic_udev_rules is defined }}"
  loop_control:
    label: "{{ item.name }}"
    