- name: set timezone to {{timezone}}
  timezone:
    name: "{{timezone}}"
  when: kernel.rc is defined and kernel.rc  # avoid WSL2

# NOT NEED with plugin timezone
# - name: linklocaltime
#   ansible.builtin.file:
#     src: /usr/share/zoneinfo/Europe/Brussels
#     dest: /etc/localtime
#     state: link

- name: check NTP active
  command: timedatectl show --property=NTP --value
  register: ntp_status
  changed_when: false
  when: kernel.rc is defined and kernel.rc  # avoid WSL2
# TODO COND IF systemd-timesyncd IS INSTALLED
# - name: enable ntp
#   command: timedatectl set-ntp true
#   when: kernel.rc is defined and kernel.rc and ntp_status.stdout != 'yes'