- name: create root SSH dir /root/.ssh
  file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: generate root SSH key "{{ssh_key_filename}}"
  openssh_keypair:
    path: "/root/.ssh/{{ssh_key_filename}}"
    type: ed25519
    size: 4096
    state: present
    force: false
- name: Adjust prohibit-password root setting in /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
  notify: reload sshd
  when: kernel.rc is defined and kernel.rc # avoid WSL2

- name: sudo session timeout
  copy:
    dest: /etc/sudoers.d/custom_defaults
    validate: "visudo -cf %s"
    mode: 0440
    content: |
      Defaults timestamp_timeout={{basic_sudo_timeout}}

- name: passwordless for sudo group
  lineinfile:
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
    regexp: "^%sudo ALL="
    path: "/etc/sudoers"
    validate: "visudo -cf %s"
  when: basic_sudo_passwordless is defined and basic_sudo_passwordless == true