# - name: group "{{firstusergroup}}"
#   group:
#     name: "{{firstusergroup}}"
#     state: present
#   when: firstusergroup is defined
# - name: create user {{firstuser}}
#   user:
#     name: "{{ firstuser}}"
#     group: "{{firstusergroup}}"
#     groups: sudo,users,staff,adm
#     state: present
#     expires: -1
#     home: "{{firstuserdir}}"
#     shell: "{{firstusershell}}"
#     create_home: yes
#     system: no
#     append: yes
#     password: "{{firstuserpasswd}}"
#     generate_ssh_key: yes
#     ssh_key_type: rsa
#     ssh_key_bits: 4096
#     ssh_key_comment: "{{firstuser}} on {{ansible_hostname}}"
#   when: firstuser is defined and firstusergroup is defined 
# - name: copy public keys to user {{firstuser}}
#   authorized_key:
#     user: "{{firstuser}}"
#     state: present
#     key: "{{lookup('file',item)}}"
#   loop: "{{firstuser_public_keys}}"
#   when: firstuser_public_keys is defined
- name: copy public keys to user root
  authorized_key:
    user: root
    state: present
    key: "{{lookup('file',item)}}"
  loop: "{{root_public_keys}}"
  when: root_public_keys is defined


- name: create users 
  user:
    name: "{{item.name}}"
    group: "{{omit if item.primarygroup is not defined or item.primarygroup}}"
    groups: "{{omit if item.groups is not defined or item.groups}}"
    state: present
    expires: -1
    home: "{{item.home|default(('/home/'+ item.name))}}"
    shell: "{{item.shell|default('/bin/bash')}}"
    create_home: "{{item.create_home|default(true)}}"
    system: "{{item.system|default(false)}}"
    append: "{{omit if item.groups is not defined or true}}"
    password: "{{omit if item.passwd is not defined or item.passwd}}"
    generate_ssh_key: "{{item.generate_ssh_key|default(false)}}"
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_comment: "{{item.name}} on {{ansible_hostname}}"
  loop: "{{basic_list_users_all}}"

- name: Check users that have pubkeys
  include_tasks: ssh_keys.yml
  loop: "{{basic_list_users_all}}"
  loop_control:
    loop_var: basic_loop_user
    label: "{{basic_loop_user.name}}}}"
  when: basic_loop_user.pubkeys is defined
  