# usage ansible-playbook playbooks/install-basic.yml -e 'bm=1'
- name: Install basic package
  apt:
    pkg: "{{basic_packages}}"
    state: latest
    update_cache: true

- name: Install package for Debian >=11 or Ubuntu >= 20.04
  apt:
    pkg: "{{basic_packages_min_bullseye}}"
    state: latest
    update_cache: true
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version >= "11")
    or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "20")

- name: Install BM
  apt:
    pkg: "{{basic_packages_bm}}"
    state: latest
  when: bm