---
- import_tasks: install-basic.yml
  become: yes
- import_tasks: create-users.yml
  become: yes
- import_tasks: configure-alias.yml
- import_tasks: configure-vim.yml
  become: yes
- import_tasks: ssh.yml
  become: yes
- import_tasks: configure-time.yml
  become: yes
