---
- import_tasks: install-basic.yml
  become: true
  tags: [install]
- import_tasks: create-users.yml
  become: true
  when: basic_shared
  tags: [install]
- import_tasks: configure-alias.yml
  become: true
  when: bash_alias_shared
- import_tasks: configure-alias.yml
  when: not bash_alias_shared
  tags: [configure]
- import_tasks: configure-vim.yml
  tags: [configure]
  become: true
  when: vim_config_shared
- import_tasks: configure-vim.yml
  tags: [configure]
  when: not vim_config_shared
- import_tasks: configure-root.yml
  become: true
  when: basic_shared
  tags: [install]
- import_tasks: configure-time.yml
  become: true
  tags: [configure]
- import_tasks: configure-custom-scripts.yml
  become: true
  tags: [configure]
- import_tasks: configure-udev.yml
  become: true
  tags: [configure]
- import_tasks: configure-custom-systemd.yml
  become: true
  tags: [configure]
- import_tasks: unattended-upgrades.yml
  become: true
  tags: [configure]