- name: Install unattended-upgrades
  apt:
    pkg:
      - unattended-upgrades
    state: latest
    update_cache: true
  when: basic_auto_upgrade is defined and basic_auto_upgrade

- name: Unattended autoclean and reboot
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    marker : "// {mark} ANSIBLE block"
    insertafter: EOF
    backup: false
    block: |
      Unattended-Upgrade::Mail "root";
      Unattended-Upgrade::MailOnlyOnError "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
  when: basic_auto_upgrade is defined and basic_auto_upgrade and ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "20"

#TODO debian add file FAILED! => {"changed": false, "msg": "Path /etc/apt/apt.conf.d/50unattended-upgrades does not exist !", "rc": 257}