- name: Install unattended-upgrades
  apt:
    pkg:
      - unattended-upgrades
    state: latest
    update_cache: yes
  when: auto_upgrade is defined and auto_upgrade

- name: Unattended autoclean and reboot
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    marker : "// {mark} ANSIBLE block"
    insertafter: EOF
    backup: no
    block: |
      Unattended-Upgrade::Mail "root";
      Unattended-Upgrade::MailOnlyOnError "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
  when: auto_upgrade is defined and auto_upgrade