---
- name: restart sshd
  systemd:
    name: sshd
    state: restarted
    daemon_reload: no
  retries: 5
  delay: 3
  register: result
  until: result.rc == 0

- name: daemon_reload
  systemd:
    daemon_reload: yes