---
- name: reload sshd
  systemd:
    name: sshd
    state: reloaded
    daemon_reload: no
  delay: 3
  register: result
  until: result.rc == 0

- name: daemon_reload
  systemd:
    daemon_reload: yes